---
- hosts: rufwebotadmin
  gather_facts: no
  become: yes
  tasks:
  - name: install dependencies for dependencies
    apt: update_cache=yes name={{ item }} state=present
    with_items:
      - build-essential
      - libssl-dev
      - libffi-dev
      - python-dev
      - python-setuptools

  - name: create directory for requirements.txt
    file: path=~/pynik_deploy state=directory

  - name: copy requirements.txt
    copy: src=requirements.txt dest=~/pynik_deploy/requirements.txt

  - name: install dependencies
    pip: requirements=~/pynik_deploy/requirements.txt

  - name: install deploy dependencies (apt)
    apt: name=screen state=present

  - name: install deploy dependencies (pip)
    pip: name=honcho

- hosts: rufwebot
  gather_facts: no
  tasks:
  - name: fetch github master
    git: repo=https://github.com/dentarg/pynik.git
         dest=~/pynik
         version=master

  - name: prepare crontab
    cronvar: name=PATH value="$PATH:/usr/local/bin" user=rufwebot

  - name: install crontab
    cron: name=rufwebotqnet special_time=reboot user=rufwebot
          job="(cd ~/pynik; screen -d -m -S tigerbot honcho run python main.py)"
